application:
  port: 8000
# Below information could be taken from the environment variable `DATABASE_URL`,
# which is used for compiling `sqlx` procedural macros
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"