name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    # We can create many these steps here, can't we?
    # 
    steps:
    - uses: actions/checkout@v4
    - name: Run the `init_db` script
    - run: |
    ./scripts/init_db.sh
    cargo check
